# Generated by Django 2.2 on 2019-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('specialty', models.CharField(max_length=200)),
                ('residence', models.CharField(max_length=100)),
                ('references', models.FileField(upload_to='uploads/%Y/%M/%D/')),
            ],
        ),
    ]
