# Generated by Django 2.2 on 2019-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='references',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
