# Generated by Django 2.2 on 2019-07-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190731_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='references',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
